<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>livestock.ico</ApplicationIcon>
	  <Version>1.0.1.21</Version> <!-- 🔺 여기를 원하는 버전으로 수정 -->
  </PropertyGroup>
  <ItemGroup>
    <None Remove="C:\Users\ktnjo\.nuget\packages\nlog.config\4.7.15\contentFiles\any\any\NLog.config" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="livestock.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="EzDotNetty" Version="1.0.21" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.0.6" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Config\Board.XML">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Config\logo.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Config\logo2.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Config\구미칠곡_users.XML">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Config\곡성_users.XML">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Config\고창부안_users.XML">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Config\users.XML">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Config\목무신_users.XML">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Config\해남_users.XML">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Config\개발_users.XML">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Config\춘천_users.XML">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\" />
    <Folder Include="Views\Size128_64\Running\CustomRunning_64\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Views\Size128_128\Running\GimjeRun.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Size128_128\Running\Standard_non_QQuri_Run1_1.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
</Project>
